[package]
name = "domain"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# json
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

approx = "0.5.0"
