[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# logging
log = "0.4.0"
env_logger = "0.9.0"

# web
actix-web = "3"

# json
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

# config
envy = "0.4.2"
dotenv = "0.15.0"

# utils 
approx = "0.5.0"
