[package]
name = "domain"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# json
serde = "1"
serde_json = "1"
serde_derive = "1"

approx = "0.5"
rand = "0.8"
chrono = "0.4"
