# rebalance
POST http://localhost:8072/v4/rebel/rebalance
Content-Type: application/json

{
  "current_portfolio": {
    "A": 75000,
    "B": 100000,
    "C": 125000
  },
  "required_allocation": {
    "A": 33,
    "B": 33,
    "C": 34
  }
}
