### rebalance

POST http://localhost:8072/v4/rebel/rebalance
Content-Type: application/json

{
  "current_portfolio": {
    "A": 75000,
    "B": 100000,
    "C": 125000
  },
  "required_allocation": {
    "A": 33,
    "B": 33,
    "C": 34
  }
}

### create user

POST http://localhost:8072/v1/users/
Content-Type: application/json

{
  "username": "kuka"
}

### create portfolio

POST http://localhost:8072/v1/portfolios/
Content-Type: application/json
X-Api-Key: oNS5KZJVhkSkazoRP8Gb35Cy3Uk7VEq3

{
  "QQQ": 10000.0,
  "TLT": 2500.0
}

### get portfolios

GET http://localhost:8072/v1/portfolios/
X-Api-Key: oNS5KZJVhkSkazoRP8Gb35Cy3Uk7VEq3
